# Generated by Django 4.1 on 2022-08-31 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('isbn', models.CharField(default=False, max_length=25)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
